SELECT 'Поликлиника',
(SELECT f.NameWithID FROM F002 AS f WHERE f.smocod = dpo.SMO)smo, 
(SELECT osd.NameWithID FROM OsobSluchDb AS osd WHERE osd.Id = dzo.OS_SLUCH_REGION)OS_SLUCH_REGION,
 SUM(dzo.SUMV) SUMV, COUNT(*) kol
FROM D3_ZSL_OMS AS dzo
JOIN D3_PACIENT_OMS AS dpo ON dpo.ID = dzo.D3_PID
JOIN D3_SCHET_OMS AS dso2 ON dso2.ID = dzo.D3_SCID
WHERE dzo.D3_SCID IN (2061,2071,2077,2083,2092,2095,2111,2115)
AND MONTH(dzo.DATE_Z_2) < dso2.[MONTH]
GROUP BY dpo.SMO, dzo.OS_SLUCH_REGION