DECLARE @XML_TEXT NVARCHAR(max);
DECLARE @idoc INT;
DECLARE @F010_ TABLE (
	KOD_TF NVARCHAR(2) NULL,
	KOD_OKATO NVARCHAR(5) NULL,
	[SUBNAME] NVARCHAR(254) NULL,
	[OKRUG] NUMERIC(1, 0) NULL,
	[DATEBEG] DATETIME NULL,
	[DATEEND] DATETIME NULL)
SELECT @XML_TEXT = t.BulkColumn
FROM    (SELECT *    
    FROM OPENROWSET (BULK '\\sqlserver\vip\F010.xml', SINGLE_CLOB) 
 AS xCol) AS t
 

SET @XML_TEXT = REPLACE(@XML_TEXT, '<?xml version="1.0" encoding="windows-1251"?>', '')
EXEC sp_xml_preparedocument @idoc OUTPUT, @XML_TEXT;
BEGIN TRY
	INSERT INTO @F010_ (KOD_TF, KOD_OKATO, SUBNAME, OKRUG, DATEBEG, DATEEND)
	SELECT KOD_TF, KOD_OKATO, SUBNAME, OKRUG, DATEBEG, DATEEND
	FROM OPENXML (@idoc, '/packet/zap', 1)
		WITH (KOD_TF NVARCHAR(2),
			  KOD_OKATO NVARCHAR(5),
			  SUBNAME NVARCHAR(254),
			  OKRUG NUMERIC(1,0), 
			  DATEBEG DATE ,
			  DATEEND DATE
			  ) T
END TRY
BEGIN CATCH
	PRINT 'Ошибка загрузки XML файла.';
END CATCH

SELECT * from @F010_