CREATE NONCLUSTERED INDEX [D3_SCIDOS_SLUCH_REGION]
ON [dbo].[D3_ZSL_OMS] ([D3_SCID],[OS_SLUCH_REGION])
INCLUDE ([ID],[D3_PID],[SUMV])
GO
CREATE NONCLUSTERED INDEX [USL_OKP_CEL]
ON [dbo].[D3_SL_OMS] ([USL_OK],[P_CEL])
INCLUDE ([D3_ZSLID],[PROFIL],[DATE_2],[DS1])
GO
CREATE NONCLUSTERED INDEX [FAMIMOTDR]
ON [dbo].[D3_PACIENT_OMS] ([FAM],[IM],[OT],[DR])
INCLUDE ([ID])
GO
CREATE NONCLUSTERED INDEX [USL_OKDATE_2DS1]
ON [dbo].[D3_SL_OMS] ([USL_OK],[DATE_2],[DS1])
INCLUDE ([ID],[D3_ZSLID],[PROFIL])
GO
CREATE NONCLUSTERED INDEX [USLOK]
ON [dbo].[D3_SL_OMS] ([USL_OK])
INCLUDE ([ID],[D3_ZSLID],[PROFIL],[DATE_2],[DS1])
GO
CREATE NONCLUSTERED INDEX [D3_ZSLIDUSL_OKP_CEL]
ON [dbo].[D3_SL_OMS] ([D3_ZSLID],[USL_OK],[P_CEL])
INCLUDE ([PROFIL],[DATE_2],[DS1])
GO
CREATE NONCLUSTERED INDEX [USLOK]
ON [dbo].[D3_ZSL_OMS] ([USL_OK])
INCLUDE ([ID],[D3_PID],[LPU],[OS_SLUCH_REGION],[SUMV])
GO
CREATE NONCLUSTERED INDEX [IDD3_PIDLPUOS_SLUCH_REGIONSUMV]
ON [dbo].[D3_ZSL_OMS] ([USL_OK])
INCLUDE ([ID],[D3_PID],[LPU],[OS_SLUCH_REGION],[SUMV])
GO