
SELECT m.NOM, m.PRENOM, COUNT (*)
FROM(
SELECT 
DISTINCT
--MOTCONSU.MOTCONSU_ID, MOTCONSU.MOTCONSU_EV_ID,
--MOTCONSU_ev.MOTCONSU_ID, MOTCONSU_EV.MOTCONSU_EV_ID,
--MOTCONSU.KRN_GUID, MOTCONSU_EV.KRN_GUID,
----------//начало persan//-----------
PATIENTS.PATIENTS_ID ID_PAC, --Код записи о пациенте
PATIENTS.NOM FAM, --Фамилия пациента
PATIENTS.PRENOM IM, --Имя пациента
PATIENTS.PATRONYME OT,-- Отчество пациента
(CASE	WHEN PATIENTS.POL = 0 THEN 1
		WHEN PATIENTS.POL = 1 THEN 2 
		ELSE 3 END) W, --Пол пациента
PATIENTS.NE_LE DR, PATIENTS.TEL, NULL DOST, --Код надёжности идентификации пациента
NULL FAM_P, NULL IM_P, NULL OT_P, NULL W_P, NULL DR_P, NULL DOST_P,
NULL MR, 
(CASE	WHEN PATIENTS.VID_DOKUMENTA = 10 THEN 3
		WHEN PATIENTS.VID_DOKUMENTA = 21 THEN 14 
		ELSE 28 END) DOCTYPE, 
PATIENTS.SERIQ_DOKUMENTA AS DOCSER, -- Серия документа, удостоверяющего личность пациента или представителя
PATIENTS.PASPORT_N AS DOCNUM,  --Номер документа, удостоверяющего личность пациента или представителя
KEM_V_DAN [DOCORG],
KOGDA_V_DAN [DOCDATE],
CASE WHEN PATIENTS.SNILS='' THEN NULL ELSE PATIENTS.SNILS END AS SNILS, --СНИЛС пациента или представителя
NULL OKATOG, --Код места жительства по ОКАТО
NULL OKATOP, --Код места пребывания по ОКАТО
-----//конец persan//-----------

--------//начало Сведения о пациенте//--------
CASE WHEN DIPO.SERIQ_POLISA = '' THEN NULL ELSE DIPO.SERIQ_POLISA END AS DocS1, -- Серия документа, подтверждающего факт страхования по ОМС
DIPO.NOMER_POLISA AS DocN1, -- Номер документа, подтверждающего факт страхования по ОМС
NULL ST_OKATO, --Регион страхования  Указывается ОКАТО территории выдачи ДПФС для полисов старого образца при наличии данных
ORG.CODE_OMS AS SMO, -- Реестровый номер СМО. 
ORG.ORGN SMO_OGRN, --ОГРН СМО
NULL SMO_OK, --ОКАТО территории страхования 
ORG.SHORT_LABEL AS SMO_NAM, --Наименование СМО
NULL NOVOR, --Признак новорождённого
--------//конец Сведения о пациенте//--------

----//начало Сведения о законченном случае//----
MOTCONSU_EV.MOTCONSU_ID IDCASE, --Номер записи в реестре случаев
3 USL_OK, --условие оказание мед. помощи
--doc.vidpom VIDPOM, --Вид медицинской помощи подскавлю из справочника врача
--CASE WHEN SUBSTRING(OMS_CODE,11,1) = '3' AND MKB.CODE NOT LIKE 'Z%' THEN 2 ELSE CAST(DATA_AMBULAT_PATIENT_COUPON.ED_AIDINGS_FORMS_ID AS INT) END FOR_POM, --Форма оказания медицинской помощи
DATA_AMBULAT_PATIENT_COUPON.OMS_V014_ID FOR_POM,
NULL NPR_MO, --Код МО, направившей на лечение (диагностику, консультацию, госпитализацию)
NULL NPR_DATE, --Дата направления на лечение (диагностику, консультацию, госпитализацию)
--@lpu LPU, --Код МО
CAst(MOTCONSU_EV.DATE_CONSULTATION as date) DATE_Z_1,  cast(MOTCONSU_EV.EV_DATE_CLOSE as date) DATE_Z_2,
NULL KD_Z, --Продолжительность госпитализации (койко-дни/пациенто-дни)
NULL VNOV_M, --Вес при рождении
 CASE WHEN MOTCONSU.DATE_CONSULTATION >= '20191010' AND ED_TREATMENT_RESULT_CODE IS NULL THEN ov5.IDRMP
      	ELSE CAST(ED_TREATMENT_RESULT_CODE AS INT) END AS [RSLT], --Результат обращения
      CASE WHEN MOTCONSU.DATE_CONSULTATION >= '20191010' AND ED_OUTCOMES_CODE IS NULL THEN ov4.IDIZ 
      	ELSE CAST(ED_OUTCOMES_CODE AS INT ) END AS [ISHOD], --Исход заболевания
NULL OS_SLUCH, --Признак Особый случай при регистрации обращения за медицинской помощью
NULL VB_P, --Признак внутрибольничного перевода

----//начало Сведения о случае//----
MOTCONSU.KRN_GUID SL_ID, --Идентификатор случая
CAST(301 AS NVARCHAR(3)) LPU_1, --Подразделение МО
NULL PODR, --Код отделения
--doc.profil PROFIL, --Профиль медицинской помощи
NULL PROFIL_K, --Профиль койки
--doc.det DET, --Признак детского профиля
CASE WHEN CAST(MOTCONSU.DATE_CONSULTATION AS DATE) < = '20191009' THEN 
	CASE WHEN CAST(DATA_AMBULAT_PATIENT_COUPON.ED_AIDINGS_FORMS_ID AS INT) = 2 THEN '1.1'
ELSE
	CASE WHEN SUBSTRING(OMS_CODE,11,1) = '1' AND MKB.CODE NOT LIKE 'Z%' THEN '1.0'     
		 WHEN SUBSTRING(OMS_CODE,11,1) = '2' AND MKB.CODE LIKE 'Z%' THEN '2.1' 
		 WHEN SUBSTRING(OMS_CODE,11,1) = '3' AND MKB.CODE NOT LIKE 'Z%' THEN '1.1' ELSE 
		 	CASE WHEN MKB.CODE LIKE 'Z%' THEN '2.1' ELSE '1.0' END 
	END END	 
	ELSE  ov2.IDPC END P_CEL,--Цель посещения

CAST(DATA_AMBULAT_PATIENT_COUPON.DATA164_ID AS VARCHAR(50)) NHISTORY,--Номер истории болезни/ талона амбулаторного пациента/ карты вызова скорой медицинской помощи
NULL P_PER, --Признак поступления/ перевода
CAST(MOTCONSU.DATE_CONSULTATION AS DATE) DATE_1,  CAST(MOTCONSU.DATE_CONSULTATION AS DATE) DATE_2,
NULL KD, --Продолжительность госпитализации (койко-дни/пациенто-дни)
MKB1.CODE DS0,
MKB.CODE AS DS1,
NULL DS2, 
CASE WHEN MKB.CODE LIKE 'Z%' THEN NULL ELSE 
	CASE WHEN dd.STATISTIKA = 0 THEN 1  
	     WHEN dd.STATISTIKA = 1 THEN 2
	     WHEN dd.STATISTIKA = 2 THEN 3
	     ELSE 1 END END C_ZAB,--Характер основного заболевания
CASE WHEN DATA_AMBULAT_PATIENT_COUPON.DN = 0 THEN 1 
     WHEN DATA_AMBULAT_PATIENT_COUPON.DN = 1 THEN 2
     WHEN DATA_AMBULAT_PATIENT_COUPON.DN = 2 THEN 3
     WHEN DATA_AMBULAT_PATIENT_COUPON.DN = 3 THEN 4
     WHEN DATA_AMBULAT_PATIENT_COUPON.DN = 4 THEN 6
     ELSE DATA_AMBULAT_PATIENT_COUPON.DN END DN,          
NULL CODE_MES1,
NULL CODE_MES2,
NULL KSG_KPG, 
NULL REAB,
--doc.prvs PRVS,
'V021' VERS_SPEC, 
medecins.SNILS IDDOKT,
NULL ED_COL,
NULL TARIF, 
----//конец Сведения о случае//----



CASE WHEN ORG.CODE_OMS LIKE '46%' AND DATA_AMBULAT_PATIENT_COUPON.ED_AIDINGS_FORMS_ID != 2 THEN 25 
	 WHEN                             DATA_AMBULAT_PATIENT_COUPON.ED_AIDINGS_FORMS_ID  = 2 THEN 29	 
ELSE 25 END IDSP, --Код способа оплаты медицинской помощи
NULL SUMV, --Сумма, выставленная к оплате
NULL OPLATA, --Тип оплаты
NULL SUMP, --Сумма, принятая к оплате СМО (ТФОМС)
NULL SANK_IT --Сумма санкций по законченному случаю

----//конец Сведения о законченном случае//----
--,doc.NAME
--INTO reestrmedialog042019_1

FROM dbo.FM_BILL
JOIN dbo.FM_BILLDET on FM_BILL.FM_BILL_ID = FM_BILLDET.FM_BILL_ID
LEFT JOIN MEDECINS MEDECINS_SERV on FM_BILLDET.MEDECINS_ID = MEDECINS_SERV.MEDECINS_ID
LEFT JOIN dbo.FM_SERV on FM_SERV.FM_SERV_ID = FM_BILLDET.FM_SERV_ID
JOIN MOTCONSU on FM_BILL.MOTCONSU_ID = MOTCONSU.MOTCONSU_ID
JOIN MOTCONSU MOTCONSU_EV on MOTCONSU_EV.MOTCONSU_ID = FM_BILL.MOTCONSU_EV_ID
JOIN DATA_AMBULAT_PATIENT_COUPON ON DATA_AMBULAT_PATIENT_COUPON.MOTCONSU_ID = MOTCONSU_EV.MOTCONSU_ID
LEFT JOIN MEDDEP ON MEDDEP.MEDDEP_ID = ISNULL(DATA_AMBULAT_PATIENT_COUPON.VRACH_OTDELENIE, MOTCONSU_EV.MEDDEP_ID)
JOIN MEDECINS on MEDECINS.MEDECINS_ID = MOTCONSU_EV.MEDECINS_ID
JOIN PATIENTS on PATIENTS.PATIENTS_ID = MOTCONSU.PATIENTS_ID
LEFT JOIN (SELECT * FROM DATA_INS_POLICIES_OMI WITH (NOLOCK) WHERE IS_MAIN = 1 ) DIPO ON DIPO.PATIENTS_ID = PATIENTS.PATIENTS_ID
LEFT JOIN FM_ORG ORG WITH (NOLOCK) ON ORG.FM_ORG_ID = DIPO.SMO
LEFT JOIN DATA_DIAGNOSIS DD on DD.MOTCONSU_ID = MOTCONSU.MOTCONSU_ID AND dd.VID_ZABOLEVANIQ = 0 AND DD.N_LINE = 1
LEFT JOIN CIM10 MKB on MKB.CIM10_ID = DD.SS_LKA_CIM10
LEFT JOIN DATA_DIAGNOSIS DD1 on DD.MOTCONSU_ID = MOTCONSU_EV.MOTCONSU_ID AND dd.VID_ZABOLEVANIQ = 2
LEFT JOIN CIM10 MKB1 on MKB1.CIM10_ID = DD1.SS_LKA_CIM10
LEFT JOIN FM_DEP on FM_DEP.FM_DEP_ID = ISNULL(MEDDEP.FM_DEP_ID, MOTCONSU_EV.FM_DEP_ID)
LEFT JOIN ED_TREATMENT_RESULTS ED_TREATMENT_RESULTS ON ED_TREATMENT_RESULTS.ED_TREATMENT_RESULT_ID = DATA_AMBULAT_PATIENT_COUPON.ED_TREATMENT_RESULT_ID 
LEFT JOIN ED_OUTCOMES ED_OUTCOMES ON ED_OUTCOMES.ED_OUTCOMES_ID = DATA_AMBULAT_PATIENT_COUPON.ED_OUTCOMES_ID
LEFT JOIN ED_RECEPTION_TYPES AS ert ON ert.ED_RECEPTION_TYPE_ID = DATA_AMBULAT_PATIENT_COUPON.VID_PRIEMA
LEFT JOIN OMS_V012 AS ov4 ON DATA_AMBULAT_PATIENT_COUPON.OMS_V012_ID = ov4.OMS_V012_ID
LEFT JOIN OMS_V009 AS ov5 ON DATA_AMBULAT_PATIENT_COUPON.OMS_V009_ID = ov5.OMS_V009_ID
LEFT JOIN OMS_V025 AS ov2 ON DATA_AMBULAT_PATIENT_COUPON.OMS_V025_ID = ov2.OMS_V025_ID
--JOIN @docTab doc ON doc.SNILS = MEDECINS.SNILS
WHERE CAST(MOTCONSU.DATE_CONSULTATION AS DATE) >='20211101'AND CAST(MOTCONSU.DATE_CONSULTATION AS DATE) <= '20211126'  
--AND MKB.CODE NOT LIKE 'c%' 
AND ISNULL(FM_BILLDET.CANCEL, 0) = 0 and ISNULL(FM_BILLDET.FREE_PAY, 0) = 0 AND FM_BILLDET.DONE = 1 AND isnull(FM_BILLDET.CANCEL, 0) = 0 AND isnull(FM_BILLDET.BLOCKED, 0) != 1
--ORDER BY PATIENTS.NOM, PATIENTS.PRENOM, PATIENTS.PATRONYME, cast(MOTCONSU_EV.DATE_CONSULTATION AS DATE)

) AS t
JOIN MEDECINS AS m ON m.SNILS = t.IDDOKT
WHERE 
--t.P_CEL = '1.3' or 
 t.DS1 BETWEEN 'I00' AND 'I99'
 
GROUP BY m.NOM, m.PRENOM
 