SELECT 
(SELECT mk.NameWithID FROM M001_KSG AS mk WHERE mk.IDDS = dso.DS1)DS1, COUNT(*)k
FROM D3_ZSL_OMS AS dzo
	JOIN D3_SL_OMS AS dso
	ON dso.D3_ZSLID = dzo.ID
WHERE dso.IDDOKT = '048-124-474 49'
GROUP BY dso.DS1

UNION ALL
SELECT 
(SELECT mk.NameWithID FROM M001_KSG AS mk WHERE mk.IDDS = s.DS1)DS1, COUNT(*)k
FROM SLUCH AS s	
JOIN DoctorBd AS db ON db.id = s.IDDOKTO
WHERE db.SNILS = '048-124-474 49' AND YEAR(s.DATE_2) = 2017
GROUP BY s.DS1