DECLARE @id INT = 20791
-- B04.047.002       Профилактический прием (осмотр, консультация) врача-терапевта
INSERT INTO D3_USL_OMS
(D3_SLID,
	D3_ZSLID,
	D3_SLGID,
	LPU,
	PROFIL,
	VID_VME,
	DET,
	DATE_IN,
	DATE_OUT,
	DS,
	CODE_USL,
	KOL_USL,
	PRVS,
	CODE_MD,
	VERS_SPEC
)
SELECT dso.ID, dzo.ID, dso.SL_ID, 460026, dso.PROFIL, 'A01.30.026', 0, dso.DATE_1, dso.DATE_2, dso.DS1, 'A01.30.026', 1, dso.PRVS, dso.IDDOKT, 'V021'
FROM D3_ZSL_OMS AS dzo
JOIN D3_SL_OMS AS dso ON dso.D3_ZSLID = dzo.ID
WHERE dzo.D3_SCID = @id 
AND dzo.EXP_COMENT LIKE '%нет услуг%'
AND dzo.OS_SLUCH_REGION = 4

INSERT INTO D3_USL_OMS
(D3_SLID,
	D3_ZSLID,
	D3_SLGID,
	LPU,
	PROFIL,
	VID_VME,
	DET,
	DATE_IN,
	DATE_OUT,
	DS,
	CODE_USL,
	KOL_USL,
	PRVS,
	CODE_MD,
	VERS_SPEC
)
SELECT dso.ID, dzo.ID, dso.SL_ID, 460026, dso.PROFIL, 'A05.30.014', 0, dso.DATE_1, dso.DATE_2, dso.DS1, 'A05.30.014', 1, dso.PRVS, dso.IDDOKT, 'V021'
FROM D3_ZSL_OMS AS dzo
JOIN D3_SL_OMS AS dso ON dso.D3_ZSLID = dzo.ID
WHERE dzo.D3_SCID = @id 
AND dzo.EXP_COMENT LIKE '%нет услуг%'
AND dzo.OS_SLUCH_REGION = 4

INSERT INTO D3_USL_OMS
(D3_SLID,
	D3_ZSLID,
	D3_SLGID,
	LPU,
	PROFIL,
	VID_VME,
	DET,
	DATE_IN,
	DATE_OUT,
	DS,
	CODE_USL,
	KOL_USL,
	PRVS,
	CODE_MD,
	VERS_SPEC
)
SELECT dso.ID, dzo.ID, dso.SL_ID, 460026, dso.PROFIL, 'A12.09.005', 0, dso.DATE_1, dso.DATE_2, dso.DS1, 'A12.09.005', 1, dso.PRVS, dso.IDDOKT, 'V021'
FROM D3_ZSL_OMS AS dzo
JOIN D3_SL_OMS AS dso ON dso.D3_ZSLID = dzo.ID
WHERE dzo.D3_SCID = @id 
AND dzo.EXP_COMENT LIKE '%нет услуг%'
AND dzo.OS_SLUCH_REGION = 4

INSERT INTO D3_USL_OMS
(D3_SLID,
	D3_ZSLID,
	D3_SLGID,
	LPU,
	PROFIL,
	VID_VME,
	DET,
	DATE_IN,
	DATE_OUT,
	DS,
	CODE_USL,
	KOL_USL,
	PRVS,
	CODE_MD,
	VERS_SPEC
)
SELECT dso.ID, dzo.ID, dso.SL_ID, 460026, dso.PROFIL, 'A02.07.004', 0, dso.DATE_1, dso.DATE_2, dso.DS1, 'A02.07.004', 1, dso.PRVS, dso.IDDOKT, 'V021'
FROM D3_ZSL_OMS AS dzo
JOIN D3_SL_OMS AS dso ON dso.D3_ZSLID = dzo.ID
WHERE dzo.D3_SCID = @id 
AND dzo.EXP_COMENT LIKE '%нет услуг%'
AND dzo.OS_SLUCH_REGION = 4

INSERT INTO D3_USL_OMS
(D3_SLID,
	D3_ZSLID,
	D3_SLGID,
	LPU,
	PROFIL,
	VID_VME,
	DET,
	DATE_IN,
	DATE_OUT,
	DS,
	CODE_USL,
	KOL_USL,
	PRVS,
	CODE_MD,
	VERS_SPEC
)
SELECT dso.ID, dzo.ID, dso.SL_ID, 460026, dso.PROFIL, 'A02.12.002', 0, dso.DATE_1, dso.DATE_2, dso.DS1, 'A02.12.002', 1, dso.PRVS, dso.IDDOKT, 'V021'
FROM D3_ZSL_OMS AS dzo
JOIN D3_SL_OMS AS dso ON dso.D3_ZSLID = dzo.ID
WHERE dzo.D3_SCID = @id 
AND dzo.EXP_COMENT LIKE '%нет услуг%'
AND dzo.OS_SLUCH_REGION = 4

INSERT INTO D3_USL_OMS
(D3_SLID,
	D3_ZSLID,
	D3_SLGID,
	LPU,
	PROFIL,
	VID_VME,
	DET,
	DATE_IN,
	DATE_OUT,
	DS,
	CODE_USL,
	KOL_USL,
	PRVS,
	CODE_MD,
	VERS_SPEC
)
SELECT dso.ID, dzo.ID, dso.SL_ID, 460026, dso.PROFIL, 'A09.05.026', 0, dso.DATE_1, dso.DATE_2, dso.DS1, 'A09.05.026', 1, dso.PRVS, dso.IDDOKT, 'V021'
FROM D3_ZSL_OMS AS dzo
JOIN D3_SL_OMS AS dso ON dso.D3_ZSLID = dzo.ID
WHERE dzo.D3_SCID = @id 
AND dzo.EXP_COMENT LIKE '%нет услуг%'
AND dzo.OS_SLUCH_REGION = 4

INSERT INTO D3_USL_OMS
(D3_SLID,
	D3_ZSLID,
	D3_SLGID,
	LPU,
	PROFIL,
	VID_VME,
	DET,
	DATE_IN,
	DATE_OUT,
	DS,
	CODE_USL,
	KOL_USL,
	PRVS,
	CODE_MD,
	VERS_SPEC
)
SELECT dso.ID, dzo.ID, dso.SL_ID, 460026, dso.PROFIL, 'A09.05.023', 0, dso.DATE_1, dso.DATE_2, dso.DS1, 'A09.05.023', 1, dso.PRVS, dso.IDDOKT, 'V021'
FROM D3_ZSL_OMS AS dzo
JOIN D3_SL_OMS AS dso ON dso.D3_ZSLID = dzo.ID
WHERE dzo.D3_SCID = @id 
AND dzo.EXP_COMENT LIKE '%нет услуг%'
AND dzo.OS_SLUCH_REGION = 4

INSERT INTO D3_USL_OMS
(D3_SLID,
	D3_ZSLID,
	D3_SLGID,
	LPU,
	PROFIL,
	VID_VME,
	DET,
	DATE_IN,
	DATE_OUT,
	DS,
	CODE_USL,
	KOL_USL,
	PRVS,
	CODE_MD,
	VERS_SPEC
)
SELECT dso.ID, dzo.ID, dso.SL_ID, 460026, dso.PROFIL, 'A05.10.004', 0, dso.DATE_1, dso.DATE_2, dso.DS1, 'A05.10.004', 1, dso.PRVS, dso.IDDOKT, 'V021'
FROM D3_ZSL_OMS AS dzo
JOIN D3_SL_OMS AS dso ON dso.D3_ZSLID = dzo.ID
WHERE dzo.D3_SCID = @id 
AND dzo.EXP_COMENT LIKE '%нет услуг%'
AND dzo.OS_SLUCH_REGION = 4


INSERT INTO D3_USL_OMS
(D3_SLID,
	D3_ZSLID,
	D3_SLGID,
	LPU,
	PROFIL,
	VID_VME,
	DET,
	DATE_IN,
	DATE_OUT,
	DS,
	CODE_USL,
	KOL_USL,
	PRVS,
	CODE_MD,
	VERS_SPEC
)
SELECT dso.ID, dzo.ID, dso.SL_ID, 460026, dso.PROFIL, 'A02.26.015', 0, dso.DATE_1, dso.DATE_2, dso.DS1, 'A02.26.015', 1, dso.PRVS, dso.IDDOKT, 'V021'
FROM D3_ZSL_OMS AS dzo
JOIN D3_SL_OMS AS dso ON dso.D3_ZSLID = dzo.ID
WHERE dzo.D3_SCID = @id 
AND dzo.EXP_COMENT LIKE '%нет услуг%'
AND dzo.OS_SLUCH_REGION = 4

INSERT INTO D3_USL_OMS
(D3_SLID,
	D3_ZSLID,
	D3_SLGID,
	LPU,
	PROFIL,
	VID_VME,
	DET,
	DATE_IN,
	DATE_OUT,
	DS,
	CODE_USL,
	KOL_USL,
	PRVS,
	CODE_MD,
	VERS_SPEC
)
SELECT dso.ID, dzo.ID, dso.SL_ID, 460026, dso.PROFIL, 'B04.047.002', 0, dso.DATE_1, dso.DATE_2, dso.DS1, 'B04.047.002', 1, dso.PRVS, dso.IDDOKT, 'V021'
FROM D3_ZSL_OMS AS dzo
JOIN D3_SL_OMS AS dso ON dso.D3_ZSLID = dzo.ID
WHERE dzo.D3_SCID = @id 
AND dzo.EXP_COMENT LIKE '%нет услуг%'
AND dzo.OS_SLUCH_REGION = 4

INSERT INTO D3_USL_OMS
(D3_SLID,
	D3_ZSLID,
	D3_SLGID,
	LPU,
	PROFIL,
	VID_VME,
	DET,
	DATE_IN,
	DATE_OUT,
	DS,
	CODE_USL,
	KOL_USL,
	PRVS,
	CODE_MD,
	VERS_SPEC
)
SELECT dso.ID, dzo.ID, dso.SL_ID, 460026, dso.PROFIL, 'A10.30.003', 0, dso.DATE_1, dso.DATE_2, dso.DS1, 'A10.30.003', 1, dso.PRVS, dso.IDDOKT, 'V021'
FROM D3_ZSL_OMS AS dzo
JOIN D3_SL_OMS AS dso ON dso.D3_ZSLID = dzo.ID
WHERE dzo.D3_SCID = @id 
AND dzo.EXP_COMENT LIKE '%нет услуг%'
AND dzo.OS_SLUCH_REGION = 4

UPDATE dzo SET EXP_COMENT = NULL
FROM D3_ZSL_OMS AS dzo
JOIN D3_SL_OMS AS dso ON dso.D3_ZSLID = dzo.ID
WHERE dzo.D3_SCID = @id 
AND dzo.EXP_COMENT LIKE '%нет услуг%'
AND dzo.OS_SLUCH_REGION = 4