SELECT m2.LEHAHIJ_VRAH, m2.KRN_CREATE_USER_ID, m2.MOTCONSU_ID, p.PRENOM, *
FROM DATA_W438_MSE_NAPRAV n
JOIN PATIENTS AS p ON p.PATIENTS_ID = n.PATIENTS_ID
--JOIN MOTCONSU AS m ON n.MOTCONSU_ID = m.MOTCONSU_ID
JOIN MOTCONSU AS m2 ON m2.MOTCONSU_ID = n.SLUCHAI_ZABOL
WHERE p.NOM = 'баркова'

UPDATE m SET m.LEHAHIJ_VRAH = 2600314
FROM MOTCONSU AS m
WHERE m.MOTCONSU_ID = 1302453