SELECT r.NOM, r.PRENOM, SUM(kol)
FROM(
SELECT m2.NOM, m2.PRENOM, t.PATIENTS_ID, COUNT(*)kol
FROM DATA_W403_TELEMED t
JOIN MOTCONSU AS m ON m.MOTCONSU_ID = t.MOTCONSU_ID
JOIN MEDECINS AS m2 ON m.LEHAHIJ_VRAH = m2.MEDECINS_ID
WHERE m.DATE_CONSULTATION BETWEEN '20220301' AND '20220328'
GROUP BY m2.NOM, m2.PRENOM, t.PATIENTS_ID) AS r
GROUP BY r.NOM, r.PRENOM



SELECT m2.NOM, m2.PRENOM,
CASE WHEN t.OKASANA_PO_TELEFONU IS NULL THEN 'видео' ELSE 'телефон' END , COUNT(*)-- p.NOM, p.PRENOM, t.PATIENTS_ID ,t.*--, COUNT(*)kol
FROM DATA_W403_TELEMED t
JOIN MOTCONSU AS m ON m.MOTCONSU_ID = t.MOTCONSU_ID
JOIN MEDECINS AS m2 ON m.LEHAHIJ_VRAH = m2.MEDECINS_ID
JOIN PATIENTS AS p ON p.PATIENTS_ID = m.PATIENTS_ID
WHERE m.DATE_CONSULTATION BETWEEN '20220101' AND '20220430'
GROUP BY m2.NOM, m2.PRENOM, t.OKASANA_PO_TELEFONU