SELECT 
(SELECT doc.NOM + ' ' + doc.PRENOM
   FROM MEDECINS AS doc WHERE doc.MEDECINS_ID =  m.MEDECINS_ID),
(SELECT Name  FROM [EMK].[dbo].[SprStatusSend] s WHERE s.id = m.EMK3_SENDED), 
 COUNT (*)
FROM MOTCONSU AS m (NOLOCK)
WHERE m.DATE_CONSULTATION >= '20210101' 
AND m.EMK3_SENDED IS NOT NULL
AND m.REMD_ECP_SIGN_DATA_ORG IS NOT NULL
AND m.REMD_BodyPreparedReport IS NOT null
GROUP BY m.EMK3_SENDED, m.MEDECINS_ID