SELECT *
FROM SPECIALISATION AS s
WHERE s.NAME LIKE '%зам%' AND s.SPECIALISATION_ID = 41

UPDATE s SET s.CODE_NSI_DOLZGNOST = 336
FROM SPECIALISATION AS s
WHERE s.NAME LIKE '%зам%' AND s.SPECIALISATION_ID = 41

UPDATE nd SET nd.DOLZGNOST_MED_PERSONALA = 'заместитель руководителя медицинской организации'
FROM NSI_DOLZGNOST AS nd
WHERE nd.CODE_NSI_DOLZGNOST = 336