declare @doc nvarchar(14) = '048-795-700 14'
DECLARE @D3_SCID INT = 2092
--SELECT dzo.*
--UPDATE dzo SET VIDPOM = 11, EXP_COMENT = NULL 
UPDATE duo SET PRVS = 208, PROFIL = 85
FROM D3_ZSL_OMS AS dzo
JOIN D3_SL_OMS AS dso ON dso.D3_ZSLID = dzo.ID
JOIN D3_USL_OMS AS duo ON duo.D3_SLID = dso.ID
WHERE dzo.D3_SCID = @D3_SCID AND dso.IDDOKT = @doc
--AND dzo.EXP_COMENT IS NOT NULL 
and dzo.OS_SLUCH_REGION is null

UPDATE dso SET PRVS = 208, PROFIL = 85
FROM D3_ZSL_OMS AS dzo
JOIN D3_SL_OMS AS dso ON dso.D3_ZSLID = dzo.ID
WHERE dzo.D3_SCID = @D3_SCID AND dso.IDDOKT = @doc
--AND dzo.EXP_COMENT IS NOT NULL 
and dzo.OS_SLUCH_REGION is null

UPDATE dzo SET VIDPOM = 11, EXP_COMENT = NULL 
FROM D3_ZSL_OMS AS dzo
JOIN D3_SL_OMS AS dso ON dso.D3_ZSLID = dzo.ID
WHERE dzo.D3_SCID = @D3_SCID AND dso.IDDOKT = @doc
--AND dzo.EXP_COMENT IS NOT NULL 
and dzo.OS_SLUCH_REGION is null
