--SELECT TOP 100 p.*
--FROM PATDIREC AS p
--JOIN  PATIENTS AS p2 ON p2.PATIENTS_ID = p.PATIENTS_ID
--WHERE p2.NOM = 'шумакова'
--ORDER BY p.PATDIREC_ID DESC 

SELECT fo.LABEL, t.*
FROM FM_ORG AS fo
JOIN(
SELECT 
	CASE 
    WHEN pe.FM_ORG_ID IS NOT NULL THEN (SELECT TOP 1 EXTERNAL_LIS_OID FROM FM_ORG f WHERE f.FM_ORG_ID=pe.FM_ORG_ID)
	ELSE
		CASE 
		WHEN fo.EXTERNAL_LIS_OID IS NULL THEN (SELECT TOP 1 EXTERNAL_LIS_OID FROM FM_ORG f WHERE f.FM_ORG_ID=1) 
		ELSE fo.EXTERNAL_LIS_OID END
	END GuidOrg              , pe.FM_ORG_ID  ,     fo.EXTERNAL_LIS_OID, p.MOTCONSU_ID
	FROM PATDIREC p
	JOIN PL_EXAM AS pe ON pe.PL_EXAM_ID = p.PL_EXAM_ID                      
	LEFT JOIN FM_ORG fo ON fo.FM_ORG_ID = p.FM_ORG_ID                      
	WHERE --p.MOTCONSU_ID =2036443
	p.PATDIREC_ID = 2300123
) AS t ON fo.EXTERNAL_LIS_OID = t.GuidOrg
	

SELECT 
	CASE 
    WHEN pe.FM_ORG_ID IS NOT NULL THEN (SELECT TOP 1 EXTERNAL_LIS_OID FROM FM_ORG f WHERE f.FM_ORG_ID=pe.FM_ORG_ID)
	ELSE
		CASE 
		WHEN fo.EXTERNAL_LIS_OID IS NULL THEN (SELECT TOP 1 EXTERNAL_LIS_OID FROM FM_ORG f WHERE f.FM_ORG_ID=1) 
		ELSE fo.EXTERNAL_LIS_OID END
	END GuidOrg              , fo.EXTERNAL_LIS_OID, pe.* 
	FROM PATDIREC p
	JOIN PL_EXAM AS pe ON pe.PL_EXAM_ID = p.PL_EXAM_ID                      
	LEFT JOIN FM_ORG fo ON fo.FM_ORG_ID = p.FM_ORG_ID                      
	WHERE p.MOTCONSU_ID =2034678

	

SELECT *
FROM PL_EXAM AS pe
WHERE pe.PL_EXAM_ID IN (
210010,
210091,
210044,
210090,
210082,
210054,
210030,
210050,
210073,
210066

)
                      
                      
                      
