SELECT 
(SELECT f.NameWithID FROM F003 AS f WHERE f.mcod = dso.CODE_MO)mo, 
(SELECT mk.NameWithID FROM M001_KSG AS mk WHERE mk.IDDS = dso2.DS1)ds1, 
[YEAR],
COUNT(*), SUM(sumv)
FROM D3_SCHET_OMS AS dso
JOIN D3_ZSL_OMS AS dzo ON dzo.D3_SCID = dso.ID
JOIN D3_SL_OMS AS dso2 ON dso2.D3_ZSLID = dzo.ID
WHERE dso.[YEAR] IN (2019, 2020) AND dso2.PROFIL = 75 AND dso2.PRVS = 55
GROUP BY dso.CODE_MO, dso2.DS1, dso.[YEAR]
ORDER BY CODE_MO, dso.[YEAR]