DECLARE @SCHET_ID INT = 2054
SELECT ID, 903 OSHIB, 'IDCASE' IM_POL, 'SLUCH' BAS_EL, IDCASE IDCASE, NULL IDSERV, 
	   'ƒата начала лечени€ больше даты окончани€' COMMENT
FROM SLUCH
WHERE CAST(DATE_1 AS DATE) > CAST(DATE_2 AS DATE)
and SCHET_ID = @SCHET_ID

select *
from usl
where
CAST(DATE_IN AS DATE) > CAST(DATE_OUT AS DATE)
and SCHET_ID = @SCHET_ID