DECLARE @schet_id INT = 2055
SELECT sl.id, pv.FAM, pv.IM, pv.OT, pv.DR, sl.DATE_1, sl.DATE_2, pv.DOCSER, pv.DOCNUM, sl.USL_OK, 'sl.VOPL IS NULL OR sl.VOPL != 1'
FROM SLUCH AS sl
JOIN PACIENT AS pv ON pv.ID = sl.PID
WHERE pv.SCHET_ID = @schet_id
AND (sl.VOPL IS NULL OR sl.VOPL != 1)


SELECT sl.id, pv.FAM, pv.IM, pv.OT, pv.DR, sl.DATE_1, sl.DATE_2, pv.DOCSER, pv.DOCNUM, sl.USL_OK, 'pv.DOCSER, pv.DOCNUM'
--UPDATE PACIENT SET DOCSER = NULL, DOCNUM = NULL
FROM SLUCH AS sl
JOIN PACIENT AS pv ON pv.ID = sl.PID
WHERE pv.SCHET_ID = @schet_id
AND (DOCSER = '' OR pv.DOCNUM = '' )
UNION ALL
SELECT sl.id, pv.FAM, pv.IM, pv.OT, pv.DR, sl.DATE_1, sl.DATE_2, pv.DOCSER, pv.DOCNUM, sl.USL_OK, 'pv.W = '' OR pv.DR = '' OR pv.W IS NULL OR pv.DR IS NULL'
--UPDATE PACIENT SET DOCSER = NULL, DOCNUM = NULL
FROM SLUCH AS sl
JOIN PACIENT AS pv ON pv.ID = sl.PID
WHERE pv.SCHET_ID = @schet_id
AND (pv.W = '' OR pv.DR = '' OR pv.W IS NULL OR pv.DR IS NULL)
UNION ALL
SELECT sl.id, pv.FAM, pv.IM, pv.OT, pv.DR, sl.DATE_1, sl.DATE_2, pv.DOCSER, pv.DOCNUM, sl.USL_OK, 'pv.NPOLIS = '' OR pv.NPOLIS IS NULL'
--UPDATE PACIENT SET DOCSER = NULL, DOCNUM = NULL
FROM SLUCH AS sl
JOIN PACIENT AS pv ON pv.ID = sl.PID
WHERE pv.SCHET_ID = @schet_id
AND (pv.NPOLIS = '' OR pv.NPOLIS IS NULL)
--UNION ALL
--SELECT sl.id, pv.FAM, pv.IM, pv.OT, pv.DR, sl.DATE_1, sl.DATE_2, pv.DOCSER, pv.DOCNUM, sl.USL_OK, 'sl.IDDOKT = '' OR sl.IDDOKT IS NULL'
----UPDATE PACIENT SET DOCSER = NULL, DOCNUM = NULL
--FROM SLUCH AS sl
--JOIN PACIENT AS pv ON pv.ID = sl.PID
--WHERE pv.SCHET_ID = @schet_id
--AND (sl.IDDOKT = '' OR sl.IDDOKT IS NULL)
UNION ALL
SELECT sl.id, pv.FAM, pv.IM, pv.OT, pv.DR, sl.DATE_1, sl.DATE_2, pv.DOCSER, pv.DOCNUM, sl.USL_OK, '(sl.USL_OK = '' OR sl.USL_OK IS NULL)'
--UPDATE PACIENT SET DOCSER = NULL, DOCNUM = NULL
FROM SLUCH AS sl
JOIN PACIENT AS pv ON pv.ID = sl.PID
WHERE pv.SCHET_ID = @schet_id
AND (sl.USL_OK = '' OR sl.USL_OK IS NULL)
UNION ALL
SELECT sl.id, pv.FAM, pv.IM, pv.OT, pv.DR, sl.DATE_1, sl.DATE_2, pv.DOCSER, pv.DOCNUM, sl.USL_OK, '(sl.RSLT = '' OR sl.RSLT IS NULL'
--UPDATE PACIENT SET DOCSER = NULL, DOCNUM = NULL
FROM SLUCH AS sl
JOIN PACIENT AS pv ON pv.ID = sl.PID
WHERE pv.SCHET_ID = @schet_id
AND (sl.RSLT = '' OR sl.RSLT IS NULL)
UNION ALL
SELECT sl.id, pv.FAM, pv.IM, pv.OT, pv.DR, sl.DATE_1, sl.DATE_2, pv.DOCSER, pv.DOCNUM, sl.USL_OK, 'sl.ISHOD = '' OR sl.ISHOD IS NULL'
--UPDATE PACIENT SET DOCSER = NULL, DOCNUM = NULL
FROM SLUCH AS sl
JOIN PACIENT AS pv ON pv.ID = sl.PID
WHERE pv.SCHET_ID = @schet_id
AND (sl.ISHOD = '' OR sl.ISHOD IS NULL)
UNION ALL
SELECT sl.id, pv.FAM, pv.IM, pv.OT, pv.DR, sl.DATE_1, sl.DATE_2, pv.DOCSER, pv.DOCNUM, sl.USL_OK + ' - ' + isnull(sl.OS_SLUCH_REGION, ''), 'sl.DATE_1 = '' OR sl.DATE_1 IS NULL OR sl.DATE_2 = '' OR sl.DATE_2 IS NULL'
--UPDATE PACIENT SET DOCSER = NULL, DOCNUM = NULL
FROM SLUCH AS sl
JOIN PACIENT AS pv ON pv.ID = sl.PID
WHERE pv.SCHET_ID = @schet_id
AND (sl.DATE_1 = '' OR sl.DATE_1 IS NULL OR sl.DATE_2 = '' OR sl.DATE_2 IS NULL)
UNION ALL
SELECT sl.id, pv.FAM, pv.IM, pv.OT, pv.DR, sl.DATE_1, sl.DATE_2, pv.DOCSER, pv.DOCNUM, sl.USL_OK + ' - ' + isnull(sl.OS_SLUCH_REGION, ''), 'sl.DS1 = '' OR sl.DS1 IS NULL'
--UPDATE PACIENT SET DOCSER = NULL, DOCNUM = NULL
FROM SLUCH AS sl
JOIN PACIENT AS pv ON pv.ID = sl.PID
WHERE pv.SCHET_ID = @schet_id
AND (sl.DS1 = '' OR sl.DS1 IS NULL )

--DELETE FROM SLUCH WHERE id IN (3642205
--,3642205
--,3642205
--,3642205
--,3642205
--,3642205)