--UPDATE dpo SET VPOLIS = p.poltp, SMO = CASE WHEN p.smo = 2 THEN 46002 WHEN p.smo = 3 THEN 46003 WHEN p.smo = 4 THEN 46004 WHEN p.smo = 6 THEN 46006 ELSE NULL end
SELECT *
FROM D3_PACIENT_OMS AS dpo
JOIN (SELECT * FROM [web].[dbo].[web] WHERE dstop IS NULL) p ON p.enp = dpo.NPOLIS
WHERE dpo.D3_SCID = 2159 AND dpo.VPOLIS IS NULL