UPDATE dso SET C_ZAB = t.C_ZAB
FROM D3_ZSL_OMS AS dzo
JOIN D3_SL_OMS AS dso ON dso.D3_ZSLID = dzo.ID AND dso.C_ZAB IS NULL
JOIN(
SELECT dso.DS1 , dso.C_ZAB
FROM D3_ZSL_OMS AS dzo
  JOIN D3_SL_OMS AS dso ON dso.D3_ZSLID = dzo.ID
WHERE dzo.D3_SCID = 2136  AND dzo.OS_SLUCH_REGION IS NULL AND dso.C_ZAB IS NOT NULL
GROUP BY dso.DS1, dso.C_ZAB
) AS t ON t.DS1 = dso.DS1
WHERE dzo.D3_SCID = 2170