DECLARE @docTab TABLE (id INT, NAME NVARCHAR(50))
INSERT INTO @docTab(id,NAME)VALUES(88,'Позднякова Ю')

SELECT zsl.DATE_Z_2, ds.P_CEL, COUNT(*)
FROM [D3_ZSL] zsl
LEFT JOIN D3_SL AS ds ON zsl.ID = ds.D3_ZSLID
WHERE zsl.D3_SCID = 2068 AND ds.P_CEL IN ('1.3', '1.2', '1.1', '2.0') 
AND ds.IDDOKT = '152-428-349 54'
GROUP BY zsl.DATE_Z_2, ds.P_CEL

SELECT DATE_Z_2, COUNT(*)
FROM (
SELECT zsl.ID, zsl.DATE_Z_2
FROM [D3_ZSL] zsl
LEFT JOIN D3_SL AS ds ON zsl.ID = ds.D3_ZSLID
WHERE zsl.D3_SCID = 2068 AND ds.P_CEL IN ('3.0') 
AND ds.IDDOKT = '152-428-349 54'
GROUP BY zsl.ID, zsl.DATE_Z_2) AS t
GROUP BY DATE_Z_2