DECLARE @periodAllowCreate INT = 14
DECLARE  @dateStart DATE  = '20180417'
SELECT CAST(SPECIALISATION_ID AS NVARCHAR(50)) IdSpesiality, NAME NameSpesiality, 
		CAST(NSI_SPECIALISATION_ID AS NVARCHAR(50)) FerIdSpesiality, SUM(kol) CountFreeParticipantIE,
		SUM(kol) CountFreeTicket, NULL NearestDate, NULL LastDate
		FROM(
		SELECT ps.SPECIALISATION_ID, NSI_SPECIALISATION_ID, s.NAME, 
		(SELECT COUNT(*) FROM [dbo].[pl_GetMedecinGridFunc2](pl_Subj_ID, @dateStart, 
		DATEADD(DAY, CASE WHEN PERIOD_ALLOW_CREATE > 14 THEN @periodAllowCreate ELSE ISNULL(PERIOD_ALLOW_CREATE, @periodAllowCreate) END, CAST(@dateStart AS DATETIME) - 1), 0) AS t WHERE EType = 0) kol, 
		(NULL)mind, (NULL)maxd
		FROM PL_SUBJ AS ps
		JOIN SPECIALISATION AS s ON ps.SPECIALISATION_ID = s.SPECIALISATION_ID
		WHERE ps.FP_ACCESS = 1 AND ps.SPECIALISATION_ID IS NOT NULL
		AND s.NSI_SPECIALISATION_ID IS NOT NULL AND ps.ARCHIVE != 1
		) as t
		GROUP BY SPECIALISATION_ID, NAME, NSI_SPECIALISATION_ID	