DECLARE @SCHET_ID INT = 1050

UPDATE USL
SET
 PROFIL = CASE WHEN u.PROFIL IS NULL THEN s.PROFIL ELSE u.PROFIL END,  
 DET = CASE WHEN u.DET IS NULL THEN s.DET ELSE u.DET END,
 DATE_IN = CASE WHEN DATE_IN IS NULL THEN s.DATE_1 ELSE DATE_IN END,
 DATE_OUT = CASE WHEN DATE_OUT IS NULL THEN s.DATE_2 ELSE DATE_OUT END,
 DS = CASE WHEN DS IS NULL THEN s.DS1 ELSE DS END,
 MSPUID = CASE WHEN u.MSPUID IS NULL THEN s.MSPID ELSE u.MSPUID END,
 CODE_MDLPU = CASE WHEN CODE_MDLPU IS NULL THEN s.IDDOKTO ELSE CODE_MDLPU END 
FROM SLUCH AS s 
JOIN USL AS u ON u.SLID = s.ID
WHERE s.SCHET_ID = @SCHET_ID
AND s.IDSP = 9