UPDATE u SET    
PROFIL = CASE WHEN u.PROFIL IS NULL THEN sl.PROFIL ELSE u.PROFIL END,
DET = CASE WHEN u.DET IS NULL THEN sl.DET ELSE u.DET END,
DATE_IN = CASE WHEN u.DATE_IN IS NULL THEN sl.DATE_1 ELSE u.DATE_IN END,
DATE_OUT = CASE WHEN u.DATE_OUT IS NULL THEN sl.DATE_2 ELSE u.DATE_OUT END,
DS = CASE WHEN u.DS IS NULL THEN sl.DS1 ELSE u.DS END,
PRVS = CASE WHEN u.PRVS IS NULL THEN sl.PRVS ELSE u.PRVS END,
CODE_MD = CASE WHEN u.CODE_MD IS NULL THEN sl.IDDOKT ELSE u.CODE_MD END 
from D3_ZSL zsl
join D3_SL sl on zsl.ID = sl.D3_ZSLID
join D3_USL u ON u.D3_SLID = sl.id AND u.D3_ZSLID = zsl.ID
where zsl.D3_SCID = 2059 and sl.PROFIL in (85,86,87,88,89,90) and zsl.OS_SLUCH_REGION is NULL