SELECT dz.ID, p.FAM, p.IM, p.OT,p.DR, (SELECT TOP 1 ISNULL(db.FAM, '') + ' ' + ISNULL(im, '') + ' ' + ISNULL(ot, '')
 FROM Yamed_Spr_MedicalEmployee AS db WHERE db.SNILS = ds.IDDOKT) doc, ds.IDDOKT
FROM D3_ZSL AS dz
JOIN D3_SL AS ds ON ds.D3_ZSLID = dz.ID
JOIN PACIENT AS p ON p.ID = dz.D3_PID
WHERE dz.D3_SCID = 2059 AND ds.PRVS IS NULL

UPDATE ds SET PRVS = 30
--SELECT ds.PROFIL, ds.PRVS 
FROM D3_ZSL AS dz
JOIN D3_SL AS ds ON ds.D3_ZSLID = dz.ID
JOIN PACIENT AS p ON p.ID = dz.D3_PID
WHERE ds.IDDOKT = '034-588-295 82' AND dz.D3_SCID = 2059 AND ds.PRVS IS NULL