	SELECT 
ISNULL((SELECT f.NameWithID FROM F002 AS f WHERE f.smocod = CASE WHEN (p.SMO IS NULL OR p.SMO NOT LIKE '46%') THEN null ELSE 
	p.smo END), 'Иногородние' ) smo ,
(SELECT v.NameWithID FROM V006 AS v WHERE v.id = sl.USL_OK), 
COUNT(*), SUM(sumv)
FROM SLUCH AS sl
JOIN PACIENT AS p ON p.ID = sl.PID
JOIN SCHET AS s2 ON s2.ID = sl.SCHET_ID
WHERE s2.ID = 9 AND MONTH(sl.DATE_2) = 2
GROUP BY CASE WHEN (p.SMO IS NULL OR p.SMO NOT LIKE '46%') THEN null ELSE 
	p.smo END, sl.USL_OK
ORDER BY SMO, sl.USL_OK