DECLARE @pid INT = 3429 
DECLARE @AKT_DATE DATETIME
	DECLARE @USERID varchar(120) 
	DECLARE @SMONAME nvarchar(75) 
	DECLARE @MONAME nvarchar(250) 
	DECLARE @SCHET_NUM nvarchar(50) 
	DECLARE @POLIS_NUM nvarchar(400) 
	DECLARE @CARD_NUM nvarchar(400) 
	DECLARE @DS1 nvarchar(200) 
	DECLARE @DS2 nvarchar(200) 
	DECLARE @PERIOD1 datetime 
	DECLARE @PERIOD2 datetime 
	DECLARE @SUMV numeric(15, 2) 
	DECLARE @BOL_DLIT numeric(5, 0) 
	DECLARE @DOCT nvarchar(150) 
	DECLARE @DOC_CHECKED nvarchar(300) 
	DECLARE @ZAKL nvarchar(1000) 
	DECLARE @COD_PU nvarchar(20) 
	DECLARE @SUMP numeric(15, 2) 
	DECLARE @SUMNP numeric(15, 2) 
	DECLARE @SLID int  
	DECLARE @SANKID int  
	DECLARE @AKT_NUMBER int  
	DECLARE @SUM_MULCT numeric(15, 2)
	DECLARE @CARD_NUM1 nvarchar(400) 
	DECLARE @DS11 nvarchar(200) 
	DECLARE @DS21 nvarchar(200) 
	DECLARE @PERIOD11 nvarchar(200) 
	DECLARE @COD_PU1 nvarchar(20)	

DECLARE vendor_cursor CURSOR FOR 
SELECT [AKT_DATE],[USERID],[SMONAME],[MONAME],[SCHET_NUM],[POLIS_NUM],[CARD_NUM],[DS1],[DS2],[PERIOD1],[PERIOD2],[SUMV],[BOL_DLIT],[DOCT],[DOC_CHECKED],[ZAKL],[COD_PU],[SUMP],[SUMNP],[SLID],[SANKID],[AKT_NUMBER],[SUM_MULCT] 
From AKT_MEE_TBL
Where PID = @pid 

OPEN vendor_cursor
FETCH NEXT FROM vendor_cursor INTO @AKT_DATE,@USERID,@SMONAME,@MONAME,@SCHET_NUM,@POLIS_NUM,@CARD_NUM,@DS1,@DS2,@PERIOD1,@PERIOD2,@SUMV,@BOL_DLIT,@DOCT,@DOC_CHECKED,@ZAKL,@COD_PU,@SUMP,@SUMNP,@SLID,@SANKID,@AKT_NUMBER,@SUM_MULCT;
WHILE @@FETCH_STATUS = 0
BEGIN
	IF (isnull(@CARD_NUM, '') <> '')
	BEGIN
		SET @CARD_NUM1 = REPLACE(@CARD_NUM1, @CARD_NUM, '');
		SET @CARD_NUM1 = isnull(@CARD_NUM, '') + ', ' + isnull(@CARD_NUM1, '');
	END 
	
	IF (isnull(@DS1, '') <> '')
	BEGIN
		SET @DS11 = REPLACE(@DS11, @DS1, '');
		SET @DS11 = isnull(@DS1, '') + ', ' + isnull(@DS11, '');	
	END
	
	IF (isnull(@DS2, '') <> '')
	BEGIN
		SET @DS21 = REPLACE(@DS21, @DS2, '');
		SET @DS21 = isnull(@DS2, '') + ', ' + isnull(@DS21, '');
	END 
	SET @COD_PU1 = isnull(@COD_PU1, 0) + ', ' + isnull(@COD_PU, 0);
	
	FETCH NEXT FROM vendor_cursor INTO @AKT_DATE,@USERID,@SMONAME,@MONAME,@SCHET_NUM,@POLIS_NUM,@CARD_NUM,@DS1,@DS2,@PERIOD1,@PERIOD2,@SUMV,@BOL_DLIT,@DOCT,@DOC_CHECKED,@ZAKL,@COD_PU,@SUMP,@SUMNP,@SLID,@SANKID,@AKT_NUMBER,@SUM_MULCT;
END;

CLOSE vendor_cursor;
DEALLOCATE vendor_cursor;

SELECT @PERIOD11 = REPLACE('c ' + CONVERT(varchar (10), min([PERIOD1]), 104) + ' по ' + convert(VARCHAR(10), MAX([PERIOD2]), 104), '/', '.') 
From AKT_MEE_TBL
Where PID = @pid

SELECT MAX([AKT_DATE])[AKT_DATE], MAX([USERID])[USERID], MAX([SMONAME])[SMONAME], MAX([MONAME])[MONAME],
MAX([SCHET_NUM])[SCHET_NUM], MAX([POLIS_NUM])[POLIS_NUM], @CARD_NUM1 AS CARD_NUM, @DS11 AS DS1,
@DS21 AS DS2, @PERIOD11 AS PERIOD1,SUM(sumv) AS sumv, DATEDIFF(DAY, MIN(PERIOD1), MAX(PERIOD2)) AS BOL_DLIT, MAX([DOCT])[DOCT],
MAX([DOC_CHECKED])[DOC_CHECKED], MAX([ZAKL])[ZAKL], SUM([SUMNP])[SUMNP], @COD_PU1 AS COD_PU, SUM(SUMP)SUMP
From AKT_MEE_TBL
Where PID = @pid
