DECLARE @t TABLE(
	[ID] [int] IDENTITY(1,1) NOT NULL, 
	FAM NVARCHAR(40),
	IM NVARCHAR(40), 
	OT NVARCHAR(40), 
	DR DATETIME, 
	S_OSN NVARCHAR(20), 
	OS_SLUCH_REGION INT, 
	LPU NVARCHAR(6), 
	S_SUM NUMERIC(15, 2), 
	USERID INT)
DECLARE @t1 TABLE(
	[ID] int NOT NULL, 
	FAM NVARCHAR(40),
	IM NVARCHAR(40), 
	OT NVARCHAR(40), 
	DR DATETIME, 
	S_OSN NVARCHAR(20), 
	OS_SLUCH_REGION INT, 
	LPU NVARCHAR(6), 
	S_SUM NUMERIC(15, 2), 
	USERID INT)
DECLARE @tab TABLE(
	[ID] [int] NOT NULL,	
	FAM NVARCHAR(40),
	IM NVARCHAR(40), 
	OT NVARCHAR(40), 
	DR DATETIME, 
	S_OSN NVARCHAR(20), 
	OS_SLUCH_REGION INT, 
	LPU NVARCHAR(6), 
	S_SUM NUMERIC(15, 2), 
	USERID INT)
INSERT INTO @t (FAM, IM, OT, DR, S_OSN,OS_SLUCH_REGION, LPU, S_SUM, USERID)
SELECT FAM, IM, OT, DR, S_OSN,OS_SLUCH_REGION, LPU, sum(S_SUM) as S_SUM, aet.USERID
	FROM [SLUCH] as sl
	INNER JOIN PACIENT p on p.ID = sl.PID
	INNER JOIN SCHET sc on sl.SCHET_ID = sc.ID 
	INNER JOIN SANK s on sl.ID = s.SLID and s.S_TIP = 3
	INNER JOIN AKT_EKMP_TBL AS aet ON aet.SANKID = s.ID
	WHERE usl_ok = 3 
	--and s.S_DATE in ('__date__')
	GROUP BY FAM, IM, OT, DR, LPU, sc.ID, OS_SLUCH_REGION, S_OSN, aet.USERID
	ORDER BY FAM, IM, OT, DR, s.S_OSN	
	
DECLARE @id INT, @kol INT = 0, @k INT = 0, @FAM NVARCHAR(40),@IM NVARCHAR(40), @OT NVARCHAR(40), @DR DATETIME;
DECLARE @OSN NVARCHAR(20),@OS_SLUCH_REGION INT, @LPU NVARCHAR(6), @S_SUM NUMERIC(15, 2), @USERID INT;

DECLARE vendor_cursor CURSOR FOR 
SELECT *
FROM @t

OPEN vendor_cursor
FETCH NEXT FROM vendor_cursor INTO @id, @FAM, @IM, @OT, @DR, @OSN, @OS_SLUCH_REGION, @LPU, @S_SUM, @USERID;
WHILE @@FETCH_STATUS = 0
BEGIN
	SET @kol = 0;
	SELECT @kol = COUNT(*)
	FROM @t
	WHERE FAM = @FAM AND IM = @IM AND OT = @OT AND DR = @DR AND LPU = @LPU AND ID <> @id
	IF (@kol = 0)
	BEGIN
		INSERT INTO @tab (id, FAM, IM, OT, DR, S_OSN,OS_SLUCH_REGION, LPU, S_SUM, USERID)
		SELECT @id AS id, @FAM AS FAM, @IM AS IM, @OT AS OT, @DR AS DR, @OSN AS OSN, @OS_SLUCH_REGION AS OS_SLUCH_REGION, @LPU AS LPU, @S_SUM AS S_SUM, @USERID AS USERID
		DELETE FROM @t WHERE ID IN (SELECT ID FROM @tab AS t)			 
	END	
	IF (@kol > 0)
	BEGIN		
		INSERT INTO @t1 (id, FAM, IM, OT, DR, S_OSN, OS_SLUCH_REGION, LPU, S_SUM, USERID)
		SELECT id, FAM, IM, OT, DR, S_OSN,OS_SLUCH_REGION, LPU, S_SUM, USERID
		FROM @t
		WHERE FAM = @FAM AND IM = @IM AND OT = @OT AND DR = @DR AND LPU = @LPU
		AND OS_SLUCH_REGION IN (1, 2)		
		SET @k = 0;
		SELECT @k = COUNT(*)
		FROM @t1
		IF (@k = 2)
		BEGIN
			DELETE FROM @t WHERE ID IN (SELECT ID FROM @t1 AS t WHERE t.OS_SLUCH_REGION = 2)			
		END
		DELETE FROM @t1
		
		INSERT INTO @t1 (id, FAM, IM, OT, DR, S_OSN, OS_SLUCH_REGION, LPU, S_SUM, USERID)
		SELECT id, FAM, IM, OT, DR, S_OSN,OS_SLUCH_REGION, LPU, S_SUM, USERID
		FROM @t
		WHERE FAM = @FAM AND IM = @IM AND OT = @OT AND DR = @DR AND LPU = @LPU			
		SELECT * FROM @t1
		DELETE FROM @t WHERE ID IN (SELECT ID FROM @t1 AS t)
		
		SELECT @k = COUNT(*)
		FROM @t1 AS t
		GROUP BY t.FAM, t.IM, t.OT, t.DR, t.USERID, t.S_OSN
		--IF (@k = 2)
		--BEGIN
			
		--END
		
		DELETE FROM @t1			 
	END

	FETCH NEXT FROM vendor_cursor INTO @ID, @FAM, @IM, @OT, @DR, @OSN, @OS_SLUCH_REGION, @LPU, @S_SUM, @USERID;

END;
CLOSE vendor_cursor;
DEALLOCATE vendor_cursor

SELECT * FROM @tab
SELECT * FROM @t
