DECLARE @SCHET INT = 2055
DECLARE @SMO INT = 46001       ---Ã≈Õﬂ≈Ã —“–¿’Œ¬”ﬁ  ŒÃœ¿Õ»ﬁ

DECLARE @tt TABLE (
tt_COUNT INT,
tt_TARIF NUMERIC (15,2)
)
 
INSERT @tt VALUES (1, 362.29)
INSERT @tt VALUES (2, 724.57)
INSERT @tt VALUES (3, 1086.86)
INSERT @tt VALUES (4, 1449.15)
INSERT @tt VALUES (6, 2173.72)
INSERT @tt VALUES (7, 2536.01)
INSERT @tt VALUES (8, 2898.30)
INSERT @tt VALUES (9, 3260.58)

DECLARE @t1 TABLE (
ID INT,
sumv NUMERIC (15,2),
cnt INT
) 

INSERT INTO @t1 (id, sumv, cnt) 
SELECT ID, SUMV, sl.cnt FROM (
SELECT sl.ID, sl.SUMV, COUNT(*) cnt FROM SLUCH sl
JOIN usl u ON sl.ID = u.SLID
JOIN Nomenclature n ON u.CODE_USL = n.Id
WHERE sl.SCHET_ID = @SCHET AND sl.OS_SLUCH_REGION = 11 
AND n.Name like '%ÔËÂÏ%' 
AND u.CODE_USL != 'B04.035.004' 
GROUP BY sl.ID, sl.SUMV) sl
LEFT JOIN @tt tt ON sl.SUMV = tt.tt_TARIF
WHERE sl.cnt < tt.tt_COUNT OR sl.SUMV NOT IN (SELECT tt_TARIF FROM @tt)
SELECT * FROM @t1

UPDATE SLUCH SET SUMV = tt.tt_TARIF, TARIF = tt.tt_TARIF, SCHET_OMS_ID = (SELECT so.CODE FROM SCHET_OMS AS so WHERE so.SCHET_ID = @SCHET AND so.PLAT = p.SMO)
FROM SLUCH AS sl
JOIN PACIENT AS p ON p.ID = sl.PID
JOIN @t1 AS t1 ON t1.ID = sl.ID
JOIN @tt AS tt ON t1.cnt = tt.tt_COUNT 

DECLARE @sumv NUMERIC(15,2)
SELECT @sumv = SUM(s.SUMV) 
FROM SLUCH AS s 
JOIN PACIENT AS p ON p.ID = s.PID
WHERE s.SCHET_ID = @SCHET AND p.SMO = @SMO

UPDATE SCHET_OMS SET SUMMAV = @sumv, SUMMAP = @sumv
WHERE SCHET_ID = @SCHET AND PLAT = @SMO

DECLARE @sumv1 NUMERIC(15,2)
SELECT @sumv1 = SUM(sumv)
FROM sluch as s
WHERE s.schet_id = @SCHET

UPDATE SCHET SET SUMMAV = @sumv1 , SUMMAP = @sumv1
WHERE ID = @SCHET