-- Если таблица существует, удалить ее
IF EXISTS (SELECT * 
         FROM INFORMATION_SCHEMA.TABLES 
         WHERE TABLE_SCHEMA = USER 
         AND TABLE_NAME = 'T_VEHICULE') 
     DROP TABLE T_VEHICULE 
-- Создать таблицу
CREATE TABLE T_VEHICULE 
(VHC_ID NVARCHAR(13) NOT NULL PRIMARY KEY, 
VHC_ID_FATHER NVARCHAR(13) FOREIGN KEY REFERENCES T_VEHICULE (VHC_ID), 
VHC_NAME VARCHAR(16)) 
-- Наполнить данными
INSERT INTO T_VEHICULE VALUES (46006000, NULL, 'Дмитриевский')
INSERT INTO T_VEHICULE VALUES (4600600000200, 46006000, 'Береза') 
INSERT INTO T_VEHICULE VALUES (4600600000300, 46006000, 'Бычки') 
INSERT INTO T_VEHICULE VALUES (4600600000400, 46006000, 'Генеральшино') 
INSERT INTO T_VEHICULE VALUES (4600600000500, 46006000, 'Глубое'); 




WITH tree (data, id, level, pathstr)
AS (SELECT VHC_NAME, VHC_ID, 0, 
         CAST('' AS VARCHAR(MAX)) 
     FROM T_VEHICULE 
     WHERE VHC_ID_FATHER IS NULL 
     UNION ALL 
     SELECT VHC_NAME, VHC_ID, t.level + 1, t.pathstr + V.VHC_NAME
     FROM T_VEHICULE V 
         INNER JOIN tree t 
             ON t.id = V.VHC_ID_FATHER) 
SELECT SPACE(level) + data as data, id, level, pathstr 
FROM tree 
ORDER BY pathstr, id