SELECT
(SELECT osd.NameWithID FROM OsobSluchDb AS osd WHERE osd.Id = sl.OS_SLUCH_REGION) ,
--(SELECT v.NameWithID FROM V006 AS v WHERE v.id = sl.USL_OK), 
SUM(sl.SUMV)SUMV
FROM [SLUCH] sl
INNER JOIN PACIENT AS p ON p.ID = sl.PID
WHERE sl.SCHET_ID = 9 AND sl.USL_OK IN (3) AND sl.OS_SLUCH_REGION IN (22,11,9)
AND MONTH(sl.DATE_2) = 3
GROUP BY sl.OS_SLUCH_REGION