DECLARE @ID INT = 2092 --id счета
SELECT p.FAM, p.IM, p.OT, p.DR, 
CAST(dz.DATE_Z_1 AS DATE) DATE_Z_1, CAST(dz.DATE_Z_2 AS DATE)DATE_Z_2, 
(SELECT ysme.NameWithID FROM Yamed_Spr_MedicalEmployee AS ysme WHERE ysme.SNILS = ds.IDDOKT)IDDOKT, ds.DS1
FROM D3_ZSL_OMS AS dz
JOIN D3_PACIENT_OMS AS p ON p.ID = dz.D3_PID
JOIN D3_SL_OMS AS ds ON ds.D3_ZSLID = dz.id
JOIN D3_SCHET_OMS AS s ON s.ID = dz.D3_SCID
WHERE dz.OS_SLUCH_REGION = 22 AND MONTH(dz.DATE_Z_2) = s.[MONTH]
AND dz.D3_SCID = @ID 
AND (ds.DS1 = 'M42.1' OR ds.DS1 = 'K29.9')
ORDER BY ds.DATE_2