DECLARE @ID INT = 2868 --id счета
SELECT p.FAM, p.IM, p.OT, 
CAST(p.DR AS DATE) dr, 
CAST(dz.DATE_Z_1 AS DATE) DATE_Z_1, CAST(dz.DATE_Z_2 AS DATE)DATE_Z_2, 
(SELECT TOP 1 ysme.NameWithID FROM Yamed_Spr_MedicalEmployee AS ysme WHERE ysme.SNILS = ds.IDDOKT)IDDOKT, ds.DS1
FROM D3_ZSL_OMS AS dz
JOIN D3_PACIENT_OMS AS p ON p.ID = dz.D3_PID
JOIN D3_SL_OMS AS ds ON ds.D3_ZSLID = dz.id
JOIN D3_SCHET_OMS AS s ON s.ID = dz.D3_SCID
WHERE dz.OS_SLUCH_REGION = 4 AND dz.D3_SCID = @ID --And MONTH(dz.DATE_Z_2) = 5
ORDER BY ds.DATE_1