SELECT dzo.OS_SLUCH_REGION, COUNT(*)
FROM D3_ZSL_OMS AS dzo
JOIN D3_SCHET_OMS AS dso2 ON dso2.ID = dzo.D3_SCID
JOIN D3_PACIENT_OMS AS dpo ON dpo.ID = dzo.D3_PID
JOIN D3_SL_OMS AS dso ON dso.D3_ZSLID = dzo.ID
WHERE dso2.[MONTH] = 2 AND 
dso2.[YEAR] = 2020 AND  
dzo.OS_SLUCH_REGION IN (47,49) AND dzo.VBR = 1 
GROUP BY dzo.OS_SLUCH_REGION