DECLARE @ID INT = 2092 --id счета
SELECT YEAR(dr) dr, 
(SELECT v.NameWithID FROM V005 AS v WHERE v.Id = p.W), COUNT(*) kol
FROM D3_ZSL_OMS AS dz
JOIN D3_PACIENT_OMS AS p ON p.ID = dz.D3_PID
JOIN D3_SL_OMS AS ds ON ds.D3_ZSLID = dz.id
JOIN D3_SCHET_OMS AS s ON s.ID = dz.D3_SCID
WHERE dz.OS_SLUCH_REGION = 4 AND dz.D3_SCID = @ID --AND MONTH(dz.DATE_Z_2) = 5
GROUP BY YEAR(dr), p.W
ORDER BY DR