DECLARE @ID INT = 2152 --id счета
SELECT 
(SELECT v.NameWithID FROM V009 AS v WHERE v.IDRMP = dz.RSLT), COUNT(*)
FROM D3_ZSL_OMS AS dz
JOIN D3_SCHET_OMS AS s ON dz.D3_SCID = s.ID
WHERE dz.OS_SLUCH_REGION IN (47) AND MONTH(dz.DATE_Z_2) = s.[MONTH]
AND dz.D3_SCID = @ID 
GROUP BY dz.RSLT
