DECLARE @D3_SCID TABLE (id INT)
INSERT INTO @D3_SCID(id)
SELECT dso.ID
  FROM D3_SCHET_OMS AS dso WHERE dso.[YEAR] = 2021 AND dso.[MONTH] = 8 AND dso.NSCHET LIKE '%Сдан%'

SELECT COUNT(*), 'Всего'
FROM D3_ZSL_OMS AS dz
JOIN D3_SCHET_OMS AS ds2 ON ds2.ID = dz.D3_SCID
JOIN D3_SL_OMS AS ds ON dz.ID = ds.D3_ZSLID
WHERE dz.D3_SCID IN (SELECT id FROM @D3_SCID) AND (dz.PR_NOV = 0 OR dz.pr_nov IS NULL)
UNION ALL
SELECT COUNT(*), 'ПРоф дисп'
FROM D3_ZSL_OMS AS dz
JOIN D3_SCHET_OMS AS ds2 ON ds2.ID = dz.D3_SCID
JOIN D3_SL_OMS AS ds ON dz.ID = ds.D3_ZSLID
WHERE dz.D3_SCID IN (SELECT id FROM @D3_SCID) AND dz.OS_SLUCH_REGION IS NOT NULL AND (dz.PR_NOV = 0 OR dz.pr_nov IS NULL)

UNION ALL
SELECT COUNT(*), 'посещен. без проф. дисп.'
FROM D3_ZSL_OMS AS dz
JOIN D3_SCHET_OMS AS ds2 ON ds2.ID = dz.D3_SCID
JOIN D3_SL_OMS AS ds ON dz.ID = ds.D3_ZSLID
WHERE dz.D3_SCID IN (SELECT id FROM @D3_SCID) AND Profil NOT IN (16,28,81)  AND (dz.PR_NOV = 0 OR dz.pr_nov IS NULL)
--(16,28,72,58) 
AND dz.OS_SLUCH_REGION IS NULL 