DECLARE @D3_SCID INT = 2141
SELECT 
(SELECT v.NameWithID FROM V009 AS v WHERE v.IDRMP = dz.RSLT), COUNT(*)
FROM D3_ZSL_OMS AS dz
WHERE dz.OS_SLUCH_REGION = 11 AND dz.D3_SCID = @D3_SCID  --AND MONTH(dz.DATE_Z_2) = 1
GROUP BY dz.RSLT 

--SELECT * FROM d3
