--временная таблица tmp_D3_ZSL_OMS_koagul
USE [ElmedKokod2]
GO

/****** Object:  Table [dbo].[D3_ZSL_OMS]    Script Date: 26.09.2022 11:21:34 ******/
/*SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO
*/
CREATE TABLE [dbo].[tmp_D3_ZSL_OMS_koagul](
	--[ID] [int]  NOT NULL,
	[ZSL_ID] [nvarchar](36) NULL,
	[D3_PID] [int] NOT NULL,
	[D3_PGID] [nvarchar](36) NULL,
	[D3_SCID] [int] NOT NULL,
	[IDCASE] [numeric](11, 0) NULL,
	[VIDPOM] [int] NULL,
	[FOR_POM] [int] NULL,
	[NPR_MO] [nvarchar](6) NULL,
	[LPU] [nvarchar](6) NULL,
	[DATE_Z_1] [datetime] NULL,
	[DATE_Z_2] [datetime] NULL,
	[RSLT] [int] NULL,
	[ISHOD] [int] NULL,
	[IDSP] [int] NULL,
	[SUMV] [numeric](17, 2) NULL,
	[MTR] [bit] NOT NULL,
	[USL_OK] [int] NULL,
	[NPR_DATE] [date] NULL,
	[PR_NOV] [int] NULL,
	
	[SysDtChange] [datetime] NULL)
/*PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[D3_ZSL_OMS] ADD  DEFAULT ((0)) FOR [MTR]
GO

ALTER TABLE [dbo].[D3_ZSL_OMS] ADD  CONSTRAINT [DF_D3_ZSL_OMS_PR_NOV]  DEFAULT ((0)) FOR [PR_NOV]
GO

ALTER TABLE [dbo].[D3_ZSL_OMS] ADD  DEFAULT (getdate()) FOR [SysDtChange]
GO

ALTER TABLE [dbo].[D3_ZSL_OMS]  WITH CHECK ADD  CONSTRAINT [FK_D3_ZSL_D3_SCHET] FOREIGN KEY([D3_SCID])
REFERENCES [dbo].[D3_SCHET_OMS] ([ID])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[D3_ZSL_OMS] CHECK CONSTRAINT [FK_D3_ZSL_D3_SCHET]
GO*/
/*
ALTER TABLE [dbo].[D3_ZSL_OMS]  WITH CHECK ADD  CONSTRAINT [FK_D3_ZSL_OMS_D3_PACIENT_OMS] FOREIGN KEY([D3_PID])
REFERENCES [dbo].[D3_PACIENT_OMS] ([ID])
GO

ALTER TABLE [dbo].[D3_ZSL_OMS] CHECK CONSTRAINT [FK_D3_ZSL_OMS_D3_PACIENT_OMS]
GO


*/