DECLARE @dateStart DATETIME = '20171124'
DECLARE @periodAllowCreate INT = 1
SELECT 
	(SELECT COUNT(*) FROM [dbo].[pl_GetMedecinGridFunc2](pl_Subj_ID, @dateStart, DATEADD(DAY, ISNULL(PERIOD_ALLOW_CREATE, @periodAllowCreate), CAST(@dateStart AS DATETIME)), 0) AS t WHERE EType = 0) CountFreeParticipantIE, 
	(SELECT COUNT(*) FROM [dbo].[pl_GetMedecinGridFunc2](pl_Subj_ID, @dateStart, DATEADD(DAY, ISNULL(PERIOD_ALLOW_CREATE, @periodAllowCreate), CAST(@dateStart AS DATETIME)), 0) AS t WHERE EType = 0) CountFreeTicket, 
	ps.NAME AS Name,	
	(SELECT top 1 m.snils FROM MEDECINS AS m WHERE m.MEDECINS_ID = ps.MEDECINS_ID)Snils,
	(SELECT NAME  FROM  SPECIALISATION AS s WHERE ps.SPECIALISATION_ID = s.SPECIALISATION_ID )
	FROM PL_SUBJ AS ps
	JOIN SPECIALISATION AS s ON ps.SPECIALISATION_ID = s.SPECIALISATION_ID
	WHERE ps.FP_ACCESS = 1 --AND ps.SPECIALISATION_ID = @idSpesiality
	AND s.NSI_SPECIALISATION_ID IS NOT NULL