DECLARE @D3_SCID INT = 7045

UPDATE  du SET 
PROFIL = CASE WHEN du.PROFIL IS NULL THEN ds.PROFIL ELSE du.PROFIL END,  
 DET = CASE WHEN du.DET IS NULL THEN ds.DET ELSE du.DET END,
 DATE_IN = CASE WHEN du.DATE_IN IS NULL THEN ds.DATE_1 ELSE du.DATE_IN END,
 DATE_OUT = CASE WHEN du.DATE_OUT IS NULL THEN ds.DATE_2 ELSE du.DATE_OUT END,
 DS = CASE WHEN du.DS IS NULL THEN ds.DS1 ELSE du.DS END,
 PRVS = CASE WHEN du.PRVS IS NULL THEN ds.PRVS ELSE du.PRVS END,
 CODE_MD = CASE WHEN du.CODE_MD IS NULL THEN ds.IDDOKT ELSE du.CODE_MD END 

FROM [D3_ZSL_OMS] zsl
LEFT JOIN D3_SL_OMS AS ds ON zsl.ID = ds.D3_ZSLID
INNER JOIN D3_USL_OMS AS du ON du.D3_SLID=ds.ID AND zsl.ID=du.D3_ZSLID
WHERE zsl.D3_SCID = @D3_SCID AND ds.PROFIL IN (85,86,87,88,89,90)
 AND zsl.OS_SLUCH_REGION IS NULL
 AND zsl.IDSP IN (29,30,9)