DECLARE @SCHET_ID INT = 2057

DELETE USL 
FROM USL u
JOIN SLUCH sl on u.SLID = sl.ID
WHERE u.SCHET_ID = @SCHET_ID AND sl.USL_OK IN (3, 4)

DELETE SLUCH WHERE SCHET_ID = @SCHET_ID AND USL_OK IN (3,4) 

DELETE pacient 
FROM pacient pa 
LEFT JOIN sluch sl ON pa.id = sl.pid 
WHERE pa.SCHET_ID = @SCHET_ID AND sl.id IS NULL