UPDATE duo
SET
 PROFIL = CASE WHEN duo.PROFIL IS NULL THEN dso.PROFIL ELSE duo.PROFIL END,  
 DET = CASE WHEN duo.det IS NULL THEN dso.DET ELSE duo.DET END,
 DATE_IN = CASE WHEN DATE_IN IS NULL THEN dso.DATE_1 ELSE DATE_IN END,
 DATE_OUT = CASE WHEN DATE_OUT IS NULL THEN dso.DATE_2 ELSE DATE_OUT END,
 DS = CASE WHEN DS IS NULL THEN dso.DS1 ELSE DS END,
 PRVS = CASE WHEN duo.PRVS IS NULL THEN dso.PRVS ELSE duo.PRVS END,
 CODE_MD = CASE WHEN CODE_MD IS NULL THEN dso.IDDOKT ELSE CODE_MD END,
 CODE_USL = CASE WHEN CODE_USL IS NULL THEN duo.VID_VME ELSE CODE_USL END 
--SELECT dzo.EXP_COMENT, dso.PRVS, dso.PRVS21, *
FROM D3_ZSL_OMS AS dzo
JOIN D3_SL_OMS AS dso ON dso.D3_ZSLID = dzo.ID
JOIN D3_USL_OMS AS duo ON duo.D3_SLID = dso.ID
WHERE dzo.D3_SCID = 2141 AND dso.PROFIL IN (63,85,86,87,88,89,90)