
--UPDATE Uslugi
--SET	
-- PROFIL = CASE WHEN u.PROFIL IS NULL THEN pv.PROFIL ELSE u.PROFIL END,  
-- DetProfil = CASE WHEN u.DetProfil IS NULL THEN pv.DetProfil ELSE u.DetProfil END,
-- DateStart = CASE WHEN u.DateStart IS NULL THEN pv.HelpStart ELSE u.DateStart END,
-- DateEnd = CASE WHEN u.DateEnd IS NULL THEN pv.HelpEnd ELSE u.DateEnd END,
-- Diagnoz = CASE WHEN u.Diagnoz IS NULL THEN pv.MKB ELSE u.Diagnoz END,
-- MSPUID = CASE WHEN u.MSPUID IS NULL THEN pv.MSPID ELSE u.MSPUID END,
-- Doctor = CASE WHEN u.Doctor IS NULL THEN pv.Doctor ELSE u.Doctor END 

DECLARE @D3_SCID INT = 2060

UPDATE  du SET 
PROFIL = CASE WHEN du.PROFIL IS NULL THEN ds.PROFIL ELSE du.PROFIL END,  
 DET = CASE WHEN du.DET IS NULL THEN ds.DET ELSE du.DET END,
 DATE_IN = CASE WHEN du.DATE_IN IS NULL THEN ds.DATE_1 ELSE du.DATE_IN END,
 DATE_OUT = CASE WHEN du.DATE_OUT IS NULL THEN ds.DATE_2 ELSE du.DATE_OUT END,
 DS = CASE WHEN du.DS IS NULL THEN ds.DS1 ELSE du.DS END,
 PRVS = CASE WHEN du.PRVS IS NULL THEN ds.PRVS ELSE du.PRVS END,
 CODE_MD = CASE WHEN du.CODE_MD IS NULL THEN ds.IDDOKT ELSE du.CODE_MD END 

FROM [D3_ZSL] zsl
LEFT JOIN D3_SL AS ds ON zsl.ID = ds.D3_ZSLID
INNER JOIN D3_USL AS du ON du.D3_SLID=ds.ID AND zsl.ID=du.D3_ZSLID
WHERE zsl.D3_SCID = @D3_SCID AND ds.PROFIL IN (85,86,87,88,89,90)
 AND zsl.OS_SLUCH_REGION IS NULL
 AND zsl.IDSP IN (29,30,9)