--SELECT EXP_COMENT, dpo.* --, dzo.OS_SLUCH_REGION, *
UPDATE dpo SET DOCTYPE = NULL, DOCSER = NULL, DOCNUM = NULL
FROM D3_ZSL_OMS AS dzo
JOIN D3_PACIENT_OMS AS dpo ON dpo.ID = dzo.D3_PID
WHERE dzo.D3_SCID = 2154
AND dzo.EXP_COMENT LIKE '%99 99%'


UPDATE p SET DOCTYPE = NULL, DOCSER = NULL, DOCNUM = NULL
FROM SLUCH AS s
JOIN PACIENT AS p ON p.ID = s.PID
WHERE s.SCHET_ID = 2154
AND s.MEK_COMENT LIKE '%9999%'


--SELECT EXP_COMENT, SUBSTRING(DOCSER, 1, 2) + ' ' + SUBSTRING(DOCSER, 3, 2),DOCSER --, dzo.OS_SLUCH_REGION, *
UPDATE dpo SET DOCSER = SUBSTRING(DOCSER, 1, 2) + ' ' + SUBSTRING(DOCSER, 3, 2)
FROM D3_ZSL_OMS AS dzo
JOIN D3_PACIENT_OMS AS dpo ON dpo.ID = dzo.D3_PID
WHERE dzo.D3_SCID = 2152
AND dzo.EXP_COMENT LIKE '%99 99%'


UPDATE p SET DOCSER = SUBSTRING(DOCSER, 1, 2) + ' ' + SUBSTRING(DOCSER, 3, 2)
FROM SLUCH AS s
JOIN PACIENT AS p ON p.ID = s.PID
WHERE s.SCHET_ID = 2152
AND s.EKMP_COMENT LIKE '%99 99%'


--UPDATE dzo SET OS_SLUCH_REGION = 48
--FROM D3_ZSL_OMS AS dzo
--JOIN D3_PACIENT_OMS AS dpo ON dpo.ID = dzo.D3_PID
--WHERE dzo.D3_SCID = 2152 AND dzo.OS_SLUCH_REGION = 23