DECLARE @D3_SCID INT = 2059

UPDATE ds SET DET = CASE WHEN FLOOR(DATEDIFF(dd,dr, dz.DATE_Z_2)/365.2524) < 18 THEN 1 ELSE 0 END
FROM D3_ZSL AS dz
JOIN D3_SL AS ds ON dz.ID = ds.D3_ZSLID
JOIN PACIENT AS p ON dz.D3_PID = p.ID
WHERE ds.DET IS NULL AND dz.D3_SCID = @D3_SCID
