DECLARE @SCHET_ID INT = 2061
DECLARE @MONTH DATE = '20180430'

SELECT sl.id, FAM, IM, OT, 'Пустая дата в услуге' per 
FROM SLUCH AS sl
JOIN PACIENT AS p ON p.ID = sl.PID
JOIN USL AS u ON u.SLID = sl.ID
WHERE  
sl.USL_OK IN (1, 2) AND sl.SCHET_ID = @SCHET_ID
AND (u.DATE_IN IS NULL OR u.DATE_OUT IS NULL OR u.DATE_IN ='' OR u.DATE_OUT = '' )
UNION ALL
SELECT sl.id, FAM, IM, OT, 'Пустая дата в услуге' per 
FROM SLUCH AS sl
JOIN PACIENT AS p ON p.ID = sl.PID
WHERE sl.USL_OK IN (1, 2) AND sl.SCHET_ID = @SCHET_ID
AND (sl.DATE_1 IS NULL OR sl.DATE_2 IS NULL OR sl.DATE_1 = '' OR sl.DATE_2 = '')


SELECT sl.id, FAM, IM, OT, sl.DATE_1, sl.DATE_2, u.DATE_IN, u.DATE_OUT, 'Проверка на дату будущего' com
FROM SLUCH AS sl
JOIN PACIENT AS p ON p.ID = sl.PID
JOIN USL AS u ON u.SLID = sl.ID
WHERE  
sl.USL_OK IN (1, 2) AND sl.SCHET_ID = @SCHET_ID
AND (CAST(u.DATE_IN AS DATE) > @MONTH OR CAST(u.DATE_OUT AS DATE) > @MONTH OR 
CAST(sl.DATE_1 AS DATE) > @MONTH OR CAST(sl.DATE_2 AS DATE) > @MONTH) 