--Проверка на дату будущего
DECLARE @D3_SCID INT = 2119
DECLARE @MONTH DATE = '20181231'

SELECT DISTINCT dz.id, p.FAM, p.IM, p.OT, CAST(dz.DATE_Z_1 AS DATE)DATE_Z_1, CAST(dz.DATE_Z_2 AS DATE)DATE_Z_2, 
CAST(ds.DATE_1 AS DATE)DATE_1, CAST(ds.DATE_2 AS DATE)DATE_2, 'Проверка на дату будущего' com
FROM D3_ZSL_oms AS dz
JOIN D3_PACIENT_OMS AS p ON p.ID = dz.D3_PID
JOIN D3_SL_OMS AS ds ON dz.ID = ds.D3_ZSLID
LEFT JOIN D3_USL_OMS AS du ON du.D3_SLID = ds.ID
WHERE dz.D3_SCID = @D3_SCID AND 
 (CAST(dz.DATE_Z_1 AS DATE) > @MONTH OR CAST(dz.DATE_Z_2 AS DATE) > @MONTH OR
  CAST(ds.DATE_1 AS DATE) > @MONTH OR CAST(ds.DATE_2 AS DATE) > @MONTH OR 
  CAST(du.DATE_IN AS DATE) > @MONTH OR CAST(du.DATE_OUT AS DATE) > @MONTH) 


SELECT dz.id, p.FAM, p.IM, p.OT, CAST(dz.DATE_Z_1 AS DATE)DATE_Z_1, CAST(dz.DATE_Z_2 AS DATE)DATE_Z_2, 
CAST(ds.DATE_1 AS DATE)DATE_1, CAST(ds.DATE_2 AS DATE)DATE_2, 'Проверка на дату будущего' com
FROM D3_ZSL_OMS AS dz
JOIN D3_PACIENT_OMS AS p ON p.ID = dz.D3_PID
JOIN D3_SL_OMS AS ds ON dz.ID = ds.D3_ZSLID
WHERE dz.D3_SCID = @D3_SCID AND 
 (CAST(dz.DATE_Z_1 AS DATE) > @MONTH OR CAST(dz.DATE_Z_2 AS DATE) > @MONTH OR
  CAST(ds.DATE_1 AS DATE) > @MONTH OR CAST(ds.DATE_2 AS DATE) > @MONTH) 