DECLARE @D3_SCID INT = 2071
SELECT DISTINCT zsl.ID, p.FAM, im, ot, CAST(p.DR AS DATE) dr, CAST(zsl.DATE_Z_1 AS DATE)DATE_Z_1, CAST(DATE_Z_2 AS DATE)DATE_Z_2,
--(SELECT TOP 1 ysme.NameWithID FROM Yamed_Spr_MedicalEmployee AS ysme WHERE ysme.SNILS = ds.IDDOKT) AS doc, 
zsl.OS_SLUCH_REGION
FROM [D3_ZSL] zsl
JOIN PACIENT AS p ON p.ID = zsl.D3_PID
LEFT JOIN D3_SL AS ds ON zsl.ID = ds.D3_ZSLID
INNER JOIN D3_USL AS du ON du.D3_SLID=ds.ID AND zsl.ID=du.D3_ZSLID
WHERE zsl.D3_SCID = @D3_SCID --AND zsl.OS_SLUCH_REGION IN (22,11,9)
AND ( zsl.DATE_Z_1 IS NULL OR zsl.DATE_Z_2 IS NULL OR ds.DATE_1 IS NULL OR ds.DATE_2 IS NULL OR du.DATE_IN IS NULL OR du.DATE_OUT IS NULL)