DECLARE @snils NVARCHAR(14) = '157-451-673 85'
DECLARE @D3_SCID INT = 2059

SELECT 

(SELECT TOP 1 ysme.NameWithID FROM Yamed_Spr_MedicalEmployee AS ysme WHERE ysme.SNILS = IDDOKT)IDDOKT, IDDOKT d, t.kol, t.per
FROM(
SELECT ds.IDDOKT, COUNT(*) kol, 'посещение' per
FROM D3_ZSL AS dz
JOIN D3_SL AS ds ON ds.D3_ZSLID = dz.ID
JOIN PACIENT AS p ON p.ID = dz.D3_PID
WHERE dz.D3_SCID = @D3_SCID AND dz.OS_SLUCH_REGION IS NULL AND ds.P_CEL IN ('1.3', '3.0') 
GROUP BY ds.IDDOKT

UNION

--SELECT IDDOKT, COUNT(*) col, 'обращение' per
--FROM (
--SELECT p.FAM, p.IM, p.OT, p.DR, MAX(IDDOKT)IDDOKT
--FROM D3_ZSL AS dz
--JOIN D3_SL AS ds ON ds.D3_ZSLID = dz.ID
--JOIN PACIENT AS p ON p.ID = dz.D3_PID
--WHERE dz.D3_SCID = @D3_SCID AND dz.OS_SLUCH_REGION IS NULL AND ds.P_CEL IN ('3.0')
--GROUP BY p.FAM, p.IM, p.OT, p.DR, ds.PROFIL
--) AS t
--GROUP BY t.IDDOKT


--Неотложка
SELECT IDDOKT, COUNT(*) col, 'неотложка' per
FROM(
SELECT dz.ID, ds.IDDOKT, COUNT(*) kol--dz.ID,                
FROM D3_ZSL AS dz
JOIN D3_SL AS ds ON ds.D3_ZSLID = dz.ID
JOIN PACIENT AS p ON p.ID = dz.D3_PID
WHERE dz.D3_SCID = @D3_SCID AND dz.OS_SLUCH_REGION IS NULL AND ds.P_CEL IN ('2.0')
GROUP BY dz.ID, ds.IDDOKT) AS t
GROUP BY IDDOKT

UNION

SELECT IDDOKT, COUNT(*) col, 'профилактика' per
FROM(
SELECT dz.ID, ds.IDDOKT           
FROM D3_ZSL AS dz
JOIN D3_SL AS ds ON ds.D3_ZSLID = dz.ID
JOIN PACIENT AS p ON p.ID = dz.D3_PID
WHERE dz.D3_SCID = @D3_SCID AND dz.OS_SLUCH_REGION IS NULL AND ds.P_CEL IN ('1.1')
GROUP BY dz.ID, ds.IDDOKT) AS t
GROUP BY IDDOKT ) AS t

ORDER BY IDDOKT