--Номер текущего реестра
DECLARE @D3_SCID INT = 2152

SELECT YEAR(p.DR), 
(SELECT v.NameWithID FROM V009 AS v WHERE v.IDRMP = dz.RSLT), COUNT(*)
FROM D3_ZSL_OMS AS dz
JOIN D3_PACIENT_OMS AS p ON p.ID = dz.D3_PID
WHERE dz.D3_SCID = @D3_SCID AND dz.OS_SLUCH_REGION = 11
GROUP BY YEAR(p.DR), dz.RSLT



SELECT dso.[MONTH], COUNT(*)
FROM D3_ZSL_OMS AS dz
JOIN D3_PACIENT_OMS AS p ON p.ID = dz.D3_PID
JOIN D3_SCHET_OMS AS dso ON dso.ID = dz.D3_SCID
WHERE dz.OS_SLUCH_REGION = 11
AND dso.[YEAR] = 2020
GROUP BY dso.[MONTH]